server.servlet.context-path: "/rest-log"
springdoc.swagger-ui.path: "api"

server:
  port : 8080
  
spring:
   datasource:
      url: "jdbc:h2:mem:logdb"
      driverClassName: "org.h2.Driver"
      username: "sa"
      password: ""
   jpa:
      database-platform: "org.hibernate.dialect.H2Dialect"
      hibernate.ddl-auto: "create-drop"
      open-in-view: false
   h2:
      console:
         path: "/h2"
         enabled: true
         trace: false
         web-allow-others: false
logging:
  level:
    root: "info"